# Generated by Django 4.2.2 on 2023-07-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukou', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserClass',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastlogin',
        ),
        migrations.AddField(
            model_name='user',
            name='userSta',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userTxt',
            field=models.CharField(default=100, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userUp',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
